jenkins-plugins:
  image: rancher/jenkins-plugins:v0.1.1
jenkins-datavolume:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - chown
  - -R
  - 1000:1000
  - /var/jenkins_home
  image: busybox
  volumes:
  - /var/lib/docker/jenkins-ci:/var/jenkins_home
jenkins-primary:
  ports:
  - 8090:8080/tcp
  labels:
    io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
    io.rancher.container.hostname_override: container_name
  entrypoint:
  - /usr/share/jenkins/rancher/jenkins.sh
  image: jenkins:1.651.3
  volumes_from:
  - jenkins-plugins
  - jenkins-datavolume
