jenkins-plugins:
  scale: 1
  metadata:
    plugins: |+
      credentials
      git
      git-client
      github
      github-api
      github-oauth
      greenballs
      junit
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm

jenkins-datavolume:
  scale: 1
  metadata:
    plugins: |+
      credentials
      git
      git-client
      github
      github-api
      github-oauth
      greenballs
      junit
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm

jenkins-primary:
  scale: 1
  metadata:
    plugins: |+
      credentials
      git
      git-client
      github
      github-api
      github-oauth
      greenballs
      junit
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm

